services:
  - type: web
    name: pima-diabetes-prediction
    env: python
    plan: free
    runtime: python
    buildCommand: pip install --upgrade pip && pip install --only-binary=all --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
